### PR TITLE
Bean to configuration

### PR DESCRIPTION
**Pull request by aaron-brown**
This makes it so you don't have to use the bean as the directions state in the README. The bean is managed by the plugin itself. All that is needed is to setup the appropriate config.

It also sets a dependency to the JaxRS Plugin, to ensure that at least 0.8 is installed.

I recommend merging #13 first.

### CODE REVIEW

**Comment by aaron-brown** [comment]
I am working on another commit to this PR, so I would advise not to merge just yet, if it is able to be merged.

If not, I will rebase once I've added the commit.

Thanks.

**Comment by aruizca** [comment]
No worries! Let me know when you finish

**Comment by aaron-brown** [comment]
Updated and rebased.

**Comment by aruizca** [comment]
Thanks!

**Comment by aruizca** [comment]
Version 0.2 is now released with pretty much all your changes among others :-)

**Pull request merged**
