### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by burtbeckwith**

### CODE REVIEW

**Comment by aruizca** [comment]
Thanks you very much Burt!

**Comment by burtbeckwith** [comment]
I noticed that the jaxrs plugin is exporting the spock plugin, so I sent a PR to that project. It also seems to unnecessarily depend on 2.2+, and I dropped that to 2.0 in the PR. If they don't need 2.2 and you also don't (I don't see any reason why this plugin would) then you should upgrade to version 0.9 of jaxrs and drop your minimum to 2.0 also. When that happens you'll need to add a dependency for the spock plugin in yours - please be sure to configure it with "export = false" :)

**Comment by aruizca** [comment]
Agreed! In my case no reason to restrict only to 2.2. I will delay the final publishing till we find out about jaxrs Grails version dependency. 
I already have people asking me to backport to Grails 2.1. In fact this guy is using an older version of jaxrs (0.6) plugin just because 0.8 has the 2.2 restriction which, as you said, is probably not required.

**Comment by aruizca** [comment]
I have downgraded the Grails version to 2.0 and added spock dependencies to publish my plugin under 0.1 version. If a new version of jaxrs comes along I'll publish a new version.

**Pull request merged**
