### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kgeis**
I fixed a couple of spelling mistakes, but grammar problems remain. I couldn't figure out what words should be in that sentence.

### CODE REVIEW

**Comment by michaelrice** [comment]
It should read: `If you get a JSON body by visiting that url then you are ready to see if the Swagger-UI can reder it in your browser:`

Thats what I think anyway. Thoughts?

**Comment by kgeis** [comment]
Sounds good!  s/reder/render/

**Comment by aruizca** [comment]
Fine by me. I am not native English speaker and I wrote it pretty fast :+1: 

@kgeis Would you mind modifying your pull request with @michaelrice suggestion please?

Cheers,
Angel.

**Comment by aruizca** [comment]
Thanks @kgeis :+1:

**Pull request merged**
